name: Build and Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

# Allow write permission to GITHUB_TOKEN to commit to deploy branch.
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: All things angular
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@2272ef32f364bc80d8680ee03d8e58f126156c31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        build_configuration: production
        base_href: /dgm-lexicon/
        deploy_branch: gh-pages
        angular_dist_build_folder: dist/dgm-lexicon/browser
